Add files via upload
esx-community/esx_outlawalert pull request #4
Opened 2019-05-28 08:06 UTC by ZeProf2Code

2019-08-09 03:37 UTC, TroublesNCuddles requested changes

2019-08-09 03:37 UTC, AthenasEngineering commented on client/main.lua
> +		ESX.ShowAdvancedNotification('Centrale', '~b~Appel d\'urgence: 911~s~', '~b~Localisation : ~s~' .. streetName .. '\n~b~Infos : ~s~' .. alert, 'CHAR_CALL911', 1)
Please use locale files for this instead.

2019-08-09 03:37 UTC, AthenasEngineering commented on config.lua
> -Config = {}
What was realistically changed in this file? Spacing?

2019-10-15 18:09 UTC, ElPumpo commented
No desc?

2019-10-15 18:09 UTC, closed without merging